- name: SSH to EC2 & deploy
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.EC2_KEY }}
    script: |
      echo "➡ Removing old container"
      docker rm -f cicd-demo || true

      echo "➡ Removing old image"
      docker rmi asadchalakha/cicd-demo:latest || true

      echo "➡ Pulling latest Docker image"
      docker pull asadchalakha/cicd-demo:latest

      echo "➡ Creating secrets.json"
      echo '${{ toJson(secrets) }}' > secrets.json

      echo "➡ Converting JSON → key=value env file"
      jq -r 'to_entries | .[] | "\(.key)=\(.value)"' secrets.json > /tmp/envfile

      echo "➡ Cleaning JSON file for security"
      rm -f secrets.json

      echo "➡ Running container with env-file"
      docker run -d \
        --name cicd-demo \
        --restart always \
        --env-file /tmp/envfile \
        -p 3004:3004 \
        asadchalakha/cicd-demo:latest
